### ISSUE TITLE
Focus stop command not working

### ISSUE THREAD

**Issue by singletrackrecs** [BenniMTools/companion-module-birddog-p200#1]
Hi the module works very well. Camera control is excellent - very responsive.  

The 'focus stop' command does not work (it also has a typo 'forcus') - however when I replaced it with a custom command taken from the visca command library it does work (81 01 04 08 00 FF)

Also It would also be good to include the White Balance options in the presets or at least the command list - there are white balance presents that are useful compared to the red and blue gain, and a one-push option which I have scripted as shown in the image for a push-and-hold style operation, incase it helps anyone :)
<img width="618" alt="WB" src="https://user-images.githubusercontent.com/75907707/104137435-86658f00-5394-11eb-94a4-ccc944131e1f.png">

**Comment by BenniMTools** [comment]
Thanks for the feedback. I will take a look on it today. :-)

**Comment by BenniMTools** [comment]
Fixed. Thanks
